/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.jgroups:jgroups:5.4.12.Final")

    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // Used to serialize/deserialize byte data
    implementation("org.apache.commons:commons-lang3:3.20.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "heartbeat.reader.SensorReaderLauncher"
}

tasks.register<JavaExec>("runMonitor") {
    group = "application"
    description = "Starts the monitor process."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass = "heartbeat.monitor.Monitor"
    standardInput = System.`in`
}

tasks.register<JavaExec>("runSensorReader") {
    group = "application"
    description = "Starts the sensor reader process."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass = "heartbeat.reader.SensorReader"
    standardInput = System.`in`
}

tasks.register<JavaExec>("runSensorReaders") {
    group = "application"
    description = "Starts and supervises a sensor reader primary/backup pair."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass = "heartbeat.reader.SensorReaderLauncher"
    standardInput = System.`in`
}
